- name: Set hostname
  ansible.builtin.shell: set-prompt vault

- name: Download repo file
  ansible.builtin.shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: Install Vault
  ansible.builtin.dnf:
    name: vault
    state: started